stages:
  - Build
  - Documentation
  - Package

NET Framework 4.0:
  stage: Build
  script: "nuget restore & msbuild NChronicle.SMTP_NetFx.csproj /p:Configuration=Release"
  artifacts:
    paths:
    - bin/Release/netfx4.0/

NET Standard 2.0:
  stage: Build
  script: "dotnet build NChronicle.SMTP_NetStandard.csproj -c Release"
  artifacts:
    paths:
    - bin/Release/netstandard2.0/

Documentation:
  stage: Documentation
  script: "msbuild NChronicle.SMTP.shfbproj /p:Configuration=Release"
  dependencies:
  - NET Framework 4.0
  artifacts:
    paths:
    - _Wiki/

Package:
  stage: Package
  script: "nuget pack NChronicle.SMTP.nuspec"
  dependencies:
  - NET Framework 4.0
  - NET Standard 2.0
  artifacts:
    paths:
    - NChronicle.SMTP.*.nupkg
